django_music/music/history/urls.py
from django.urls import path

from . import views
app_name = 'history'
urlpatterns = [
    # ex: /polls/
    path('', views.SearchView.as_view(), name='all_artists' ),
    path('<int:artist_id>/', views.artist_details, name='artist_details' )
]

django_music/music/music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('history/', include('history.urls'))
]

django_music/music/history/models.py
from django.db import models

# Create your models here.

class Artist(models.Model):
    artist_name = models.CharField(max_length=50)

class Album(models.Model):
    album_name = models.CharField(max_length=50)
    album_artist = models.ForeignKey(Artist, on_delete=models.PROTECT)

class Song(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    song_name = models.CharField(max_length=50)
    song_album = models.ForeignKey(Album, on_delete=models.PROTECT)

django_music/music/history/forms.py
from django import forms

class AlbumForm(forms.Form):
    album_name = forms.CharField(label='Name of the Album', max_length=25)
    artist_name = forms.CharField(label='Name of Artist', max_length=25)

django_music/music/history/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Artist, Song, Album
from django.urls import reverse


from .forms import AlbumForm

# Using a class-based genric view especially for rendering forms
from django.views.generic.edit import FormView
from django.views.generic import ListView, TemplateView

class SearchView(FormView):
  template_name = 'music/albums.html'
  form_class = AlbumForm

  def album_artist_stuff(self):
    artist_list = Artist.objects.order_by('-id')
    album_list = Album.objects.order_by('-id')
    context = {'artist_list': artist_list,
    'album_list': album_list}
    return context

class CollectionView(TemplateView):
    template_name = 'collection_list.html'

    # Don't need to do this any more, it seems!
    # def get_context_data(self, **kwargs):
    #   # Call the base implementation first to get a context
    #   context = super().get_context_data(**kwargs)
    #   # Get the data from the API
    #   search_results = form.search()
    #   # Add in a QuerySet of the collection data
    #   context['collection'] = search_results
    #   return context
    # Because now you can define values that become props of a new 'view' object in the template
    # https://reinout.vanrees.org/weblog/2014/05/19/context.html
    def collection(self): #NOTE that it's the method name that becomes the property on 'view'
      games = ApiService.get_collection(username=self.request.GET.get('username'))
      print("games", games)
      return games

    def message(self):
      test = {"header": "this is really cool!"}
      return test






def all_artists(request):
    artist_list = Artist.objects.order_by('-id')[:5]
    album_list = Album.objects.order_by('-id')
    context = {'artist_list': artist_list,
    'album_list': album_list}
    return render(request, 'music/album.html', context)

def artist_details(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    return render(request, 'music/songs.html', {'artist': artist})

django_music/music/history/templates/music/albums.html
{% extends "music/artists.html" %}

{% block content %}

<h2>Albums</h2>

{% if view.album_artist_stuff.album_list %}
    <ul>
    {% for album in view.album_artist_stuff.album_list %}
        <li><a href="{{ album.id }}/">{{ album.album_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No albums are available.</p>
{% endif %}
<form>
    <h3>Add a New Album</h3>
    {{ form }}
    <input type="submit" value="submit">
</form>
{% endblock %}

django_music/music/history/templates/music/artists.html
{% if view.album_artist_stuff.artist_list %}
<h2>Artists</h2>
    <ul>
    {% for artist in view.album_artist_stuff.artist_list %}
        <li><a href="{{ artist.id }}/">{{ artist.artist_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No artists are available.</p>
{% endif %}

{% block content %}{% endblock %}

django_music/music/history/templates/music/songs.html
<h1>Songs by {{ artist.artist_name }}:</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<ul>
{% for song in artist.song_set.all %}
    <li>{{ song.song_name }}</li>
{% endfor %}
</ul>

<a href="{% url 'history:all_artists' %}">Find someone else?</a>